import axios from "axios";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

export default function Visualizar() {  

  const [data, setData] = useState([]);  
  
  const [message, setMessage] = useState("");

  const router = useRouter();
  //console.log(router.query.id);
  const [id] = useState(router.query.id);

  const getUser = async () => {
    if(id == undefined){
      setMessage("Erro: Usuário não encontrado!")
      return
    }
    await axios.get("http://localhost:8080/users/" + id)
    .then((response) => {
      console.log(response.data.user)  
      setData(response.data.user)
    }).catch((error) => {
        if(error.response){
          setMessage(error.response.data.mensagem);
        } else{
          setMessage("Erro! Tente novamente mais tarde!");
        }
        
      })
  }

  useEffect(() => {
    getUser();
  }, [id])
  
  return (
    <>
      <Head>
        <title>CRUD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

      <Link href={"/"}><button type="button">Listar</button></Link>{" "}
      <Link href={`/editar/${data.id}`}><button type="button">Editar</button></Link>{" "}

       <h2>Detalhes do Usuário</h2>

       {message ? <p>{message}</p> : ""}      

       <span>ID: {data.id}</span><br/> 
       <span>Nome: {data.name}</span><br/> 
       <span>Email: {data.email}</span><br/> 

      </main>
    </>
  );
}
