import axios from "axios";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

export default function Cadastrar() {

  // Declarar uma nova variável com state e atribuir o objeto com o state
  const [data, setData] = useState({
    nome:'',
    email:''
  });

  const [message, setMessage] = useState("");

  const valueInput = (e) => setData({...data,[e.target.name]: e.target.value});
  // Execuatar a função quando o usuário clicar no botão
  const addUser = async (e) => {
    e.preventDefault();
   // console.log("Enviar para API");
   // console.log("Nome do usuario " + data.name);
   // console.log("Email do usuario " + data.email);

    const headers = {
      'headers': {
        'Content-Type': 'application/json'
      }
    };
   
    await axios.post('http://localhost:8080/users', data, headers)
    .then((response) => {
      //console.log(response.data.mensagem);
      setMessage(response.data.mensagem);

      setData({
        name: '',
        email: ''
      })
    }).catch((error) => {
     // console.log(err.response.data.mensagem);

      if(err.response){
        setMessage(response.data.mensagem);
      } else{
        setMessage("Ocorreu um erro!");
      }
    })
  } 

  return (
    <>
      <Head>
        <title>CRUD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

      <Link href={"/"}><button type="button">Listar</button></Link>

       <h2>Cadastrar Usuário</h2>

       {message ? <p>{message}</p> : ""}

       <form onSubmit={addUser}>
         <label>Nome:</label>
         <input type="text" name="name" placeholder="Digite o nome" onChange={valueInput} value={data.name ?? ""}/><br/><br/>
         <label>Email:</label>
         <input type="email" name="email" placeholder="Digite o email" onChange={valueInput} value={data.email ?? ""}/><br/><br/>
         <button>Enviar</button><br/><br/>
       </form>

      </main>
    </>
  );
}
