import { serviceDelete } from "@/services/serviceDelete";
import axios from "axios";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

export default function Home() {

    const [data, setData] = useState([]);

    const [message, setMessage] = useState("");

    const getUsers = async () => {
        await axios.get("http://localhost:8080/users")
        .then((response) => {
          //console.log(response.data.users)
          setData(response.data.users);
        }).catch((error) => {
          if(error.response){
            setMessage(error.response.data.mensagem);
          } else{
            setMessage("Erro! Tente novamente mais tarde!");
          }
          
        })
    } 

    useEffect(() => {
      getUsers();
    }, []);

    const deleteUser = async (idUser) => {
       if(window.confirm('Tem certeza que deseja apagar?')){
       //  console.log(idUser)
       // chamar o serviço responsável em realizar a requisição para API
       const response = await serviceDelete('http://localhost:8080/users/' + idUser)
       setMessage(response);
       getUsers();
       } 
    }

    return (
    <>
      <Head>
        <title>CRUD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       
      <Link href={"/cadastrar"}><button type="button">Cadastrar</button></Link>

       <h2>Listar Usuários</h2>

       {message ? <p>{message}</p> : ""}
       

       {data.map(user => (
         <div key={user.id}>
          <span>ID: {user.id}</span><br/>
          <span>Nome: {user.name}</span><br/>
          <span>Email: {user.email}</span><br/><br/>
          <Link href={`/visualizar/${user.id}`}><button type="button">Visualizar</button></Link>{" "}
          <Link href={`/editar/${user.id}`}><button type="button">Editar</button></Link>{" "}
          <button type="button" onClick={()=> deleteUser(user.id)}>Apagar</button>{" "}
          <hr/>
         </div>
       ))}
      </main>
    </>
  );
}
